### ISSUE TITLE
Thanks!

### ISSUE THREAD

**Issue by r-this** [provabeer/2022-webapp-nuxt3#1]
Hello, thanks for making this public. Seeing how you wired things up helped me overcome a challenge in my project.

Your one public commit to github in the last year saved me a bunch of time. Hope you post more stuff if you're still working in the nuxt 3 sphere. 

PS, your Firebase config credentials are public in this repo. I don't know if that's a problem, I didn't try using them!

Cheers!

**Comment by provabeer** [comment]
Hello @drftls. Glad that's helped! Thanks for Firebase comment.
